# Default values for secureapp
# This is a YAML-formatted file.

# Application configuration
app:
  name: secureapp
  port: 3000
  replicas: 3
  version: 1.0.0
  nodeEnv: production

# Image configuration
image:
  repository: secureapp
  tag: latest
  pullPolicy: Always
  
# Container security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# Horizontal pod autoscaling
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Service configuration
service:
  type: ClusterIP
  port: 3000
  annotations: {}

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: secureapp.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: secureapp-tls
      hosts:
        - secureapp.example.com

# Monitoring and metrics
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 10s

# Pod affinity and anti-affinity
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - secureapp
          topologyKey: kubernetes.io/hostname

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Environment variables
env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "3000"
  - name: LOG_LEVEL
    value: info

# Secret references
secrets:
  enabled: true
  keyVault:
    enabled: true
    name: secureapp-kv
    tenantId: ""
    objects:
      - |
        objectName: JWT-SECRET
        type: secret
      - |
        objectName: DB-PASSWORD
        type: secret

# Network policies
networkPolicy:
  enabled: true
  ingressRules:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        ports:
          - port: 3000
            protocol: TCP

# Pod security policy
podSecurityPolicy:
  enabled: true